name: build & lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
    - run: yarn install
    - run: yarn build
    - run: yarn lint
    - uses: actions/upload-artifact@v2
      with:
        name: firefox_owncast_extension.zip
        path: web-ext-artifacts/*.zip
